### ISSUE TITLE
Moving devices from polar_instrument to here

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/polartools#89]
The plan is to move all devices from the instrument to here. Going forward, a new device will first go to the instrument, then, once stable, moved here.

**Comment by gfabbris** [comment]
More complicated devices that I need to look more carefully:
- counters - Make it more generic, remove the option to control time.
- energy - Make it more generic, add option to add new "energy" devices on the fly - perhaps using oregistry?
- phase plates - Separate the setup function
- diffractometer - May need to move some of the util functions as well.

**Comment by gfabbris** [comment]
Make (or already exists?) a device that just combines a bunch of motors using just kwargs.

**Comment by prjemian** [comment]
Don't know of existing

**Comment by prjemian** [comment]
I am working on one.  Similar to the `hklpy2.creator`, it accepts a list or dictionary of motors (keyed by name).  Default with no `prefix` is SoftPositioner, `prefix` is EpicsMotor.  Possible to specify a different class.  

Here's an example (what might be your initial use case):

```py
motor_device_factory(
    name="s6",
    prefix="gp:",
    motors={
        "u": m1,
        "v": m2,
        "w": m3,
    }
)
```

Other possibilities abound.  Not shown here but even where the "motors" might be some other type of positioner class (a `class="absolute.path.device.custom_positioner"`).  Starting to see some flexibility.  This will fit in well with our `devices.yml` [files](https://github.com/BCDA-APS/BITS/blob/main/src/apsbits/demo_instrument/configs/devices.yml) in BITS  (take note @Mdecarabas, @ravescovi), relieving the need to write custom motor device classes.

```yaml
- name: s1
  motors: [x, y, z]
- name: s2
  motors: [buckle, shoe]
- name: s3
  prefix: "gp:"
  motors:
    x: m1
- name: s4
  prefix: "gp:"
  motors: [x]
- name: s5
  motors:
    theta:
        prefix: gp:m3
        labels: [dcm]
    y1:
      limits: [-50, 1]
      init_pos: -15
      labels: [arm, dcm]
    z2:
      limits: [-1, 300]
      init_pos: 75
      labels: [arm, dcm]
    ty1:
      limits: [-50, 1]
      init_pos: -15
      kind: config
      labels: [table, dcm]
    ty2:
      limits: [-1, 300]
      init_pos: 75
      kind: config
      labels: [table, dcm]
```

**Comment by gfabbris** [comment]
## Problems coming out of the first try

### PRs
- Need to move callbacks to polartools and/or `pr_setup` of the pr devices file.
```python
  File "/home/beams/POLAR/.conda/envs/bluesky_2025_1-dev/lib/python3.11/site-packages/polartools/devices/phaseplates.py", line 14, in <module>
    from ..callbacks.dichro_stream import plot_dichro_settings
ModuleNotFoundError: No module named 'polartools.callbacks'
```

### Energy device relative import (obviously) doesn't work
- Use oregistry to get "track_energy" devices.

### Sydor
- Timed out on load when not connected, shouldn't do this...

### Logging missing?
- Seems like at least one of the devices is suppressing logging prints?

### Diffractometer
- Utils imports

### Logger level changed
- The logger level is changing to "error" when loading the device below. Not sure why. Looks like there was older code in that file that would change the level, but has been out since at least apstools 1.7.2, and we are using 1.7.3.
```yaml
apstools.devices.DM_WorkflowConnector:
- name: dm_workflow
  labels: ["dm"]
```
